### ISSUE TITLE
More accurate geolocation

### ISSUE THREAD

**Issue by Ironholds** [theopolisme/wikipedia-contributor-locations#1]
Want me to talk to Ops/Analytics about trying to rsync the paid dbs to labs? Seems like it could be hella-useful.

**Comment by theopolisme** [comment]
That would be great! Yes, please do & keep me posted :)

**Comment by Ironholds** [comment]
https://phabricator.wikimedia.org/T87151 boop.

**Comment by theopolisme** [comment]
@Ironholds if you're looking for more things to bug Ops about, in c55cc2 custom-rigging a `/suggest
